name: Generate AU GNAF
on:
  workflow_dispatch:
    inputs:
      url:
        description: 'URL to GNAF data'
        required: true
        default: 'https://data.gov.au/data/dataset/19432f89-dc3a-4ef3-b943-5326ef1dbecc/resource/4b084096-65e4-4c8e-abbe-5e54ff85f42f/download/may21_gnaf_pipeseparatedvalue.zip'
      tag:
        description: 'Release tag'
        required: true
        default: 'GNAF-2021-05-acttest'

jobs:
  checkout_dl:
    runs-on: ubuntu-latest
    container: osgeo/gdal:alpine-small-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Download
      id: download
      env:
        DL_PATH: ${{github.event.inputs.url}}
      run: |
        apk update
        apk upgrade
        apk add curl unzip sqlite
        mkdir tmp
        curl -L $DL_PATH > data.zip
        unzip data.zip
        mv G-NAF/G-NAF*/Standard tmp/standard
        mv G-NAF/G-NAF*/Authority* tmp/authority
    - name: Create sqlite and geojson
      run: |
        ls -lh
        ./bin/gnafall
        ls -lh
    - name: Archive GNAF geojson as artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ausgnaf-geojsonseq
        path: gnaf.*.geojson.gz
    - name: Archive GNAF geopackage as artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ausgnaf-gpkg
        path: gnaf.*.gpkg.gz
    - name: Archive GNAF sqlite as artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ausgnaf-sqlite
        path: gnaf.*.sqlite.gz
          
  mbtiles:
    runs-on: ubuntu-latest
    container: ghcr.io/jxeeno/admin-boundaries-mbtiles:tippecanoe
    needs:
      - checkout_dl
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download AUS geojson from artifacts
        uses: actions/download-artifact@v2
        with:
          name: ausgnaf-geojsonseq
      - name: Download AUS sqlite from artifacts
        uses: actions/download-artifact@v2
        with:
          name: ausgnaf-sqlite
      - name: Download AUS gpkg from artifacts
        uses: actions/download-artifact@v2
        with:
          name: ausgnaf-gpkg
      - name: Generate pmtiles
        id: download
        env:
          DL_PATH: ${{github.event.inputs.url}}
        run: |
          ls -L
          bin/generate_pmtiles_gnaf ACT &
          bin/generate_pmtiles_gnaf NT &
          bin/generate_pmtiles_gnaf TAS &
          bin/generate_pmtiles_gnaf OT &
          bin/generate_pmtiles_gnaf NSW &
          bin/generate_pmtiles_gnaf QLD &
          bin/generate_pmtiles_gnaf VIC &
          bin/generate_pmtiles_gnaf SA &
          bin/generate_pmtiles_gnaf WA &
          wait
      - name: Archive AUS pmtiles as artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ausgnaf-pmtiles
          path: gnaf.*.pmtiles.gz

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            gnaf.ACT.sqlite.gz
            gnaf.NT.sqlite.gz
            gnaf.TAS.sqlite.gz
            gnaf.OT.sqlite.gz
            gnaf.NSW.sqlite.gz
            gnaf.QLD.sqlite.gz
            gnaf.VIC.sqlite.gz
            gnaf.SA.sqlite.gz
            gnaf.WA.sqlite.gz
            gnaf.ACT.geojson.gz
            gnaf.NT.geojson.gz
            gnaf.TAS.geojson.gz
            gnaf.OT.geojson.gz
            gnaf.NSW.geojson.gz
            gnaf.QLD.geojson.gz
            gnaf.VIC.geojson.gz
            gnaf.SA.geojson.gz
            gnaf.WA.geojson.gz
            gnaf.ACT.gpkg.gz
            gnaf.NT.gpkg.gz
            gnaf.TAS.gpkg.gz
            gnaf.OT.gpkg.gz
            gnaf.NSW.gpkg.gz
            gnaf.QLD.gpkg.gz
            gnaf.VIC.gpkg.gz
            gnaf.SA.gpkg.gz
            gnaf.WA.gpkg.gz
            gnaf.ACT.pmtiles.gz
            gnaf.NT.pmtiles.gz
            gnaf.TAS.pmtiles.gz
            gnaf.OT.pmtiles.gz
            gnaf.NSW.pmtiles.gz
            gnaf.QLD.pmtiles.gz
            gnaf.VIC.pmtiles.gz
            gnaf.SA.pmtiles.gz
            gnaf.WA.pmtiles.gz
          tag_name: ${{github.event.inputs.tag}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
